{% set name = "pynauty" %}
{% set version = "2.8.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynauty-{{ version }}.tar.gz
  sha256: 454d3b0e605d649d13478afb090daef4a152f15c4a337a391fe69fded7e683f2
  patches:
    - setup.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - nauty =2.7.1
  run:
    - python
    - {{ pin_compatible('nauty', max_pin='x.x.x') }}

test:
  imports:
    - pynauty
    - pynauty.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pdobsan/pynauty
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Isomorphism testing and automorphisms of graphs
  description: |
    Pynauty can be used to compare graphs for isomorphism and to determine
    their automorphism group in a Python programming environment. Pynauty
    is a Python/C extension module using library components from the Nauty
    package by Brendan McKay.
  doc_url: https://github.com/pdobsan/pynauty
  dev_url: https://github.com/pdobsan/pynauty

extra:
  recipe-maintainers:
    - jan-janssen
